server:
  port: 7777
  error:
    include-stacktrace: never
spring:
  application:
    name: employeefull
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employeeFull
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
